version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=db_file_shared
    ports:
      - 3307:3306
    volumes:
      - todo4-mysql-data:/var/lib/mysql
      - todo4-mysql-config:/etc/mysql
  backend:
    build:
      dockerfile: Dockerfile
    environment:
      - .env
    volumes:
      - ./:/nodejs_hello
    ports:
      - "8089:8089"
    depends_on:
      - db

volumes:
  todo4-mysql-data:
  todo4-mysql-config:
